# Generated by Django 3.1 on 2022-11-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paypal',
            new_name='status',
        ),
    ]
